//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardYK.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnboardYK.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Advanced.
        /// </summary>
        internal static string menu_advanced {
            get {
                return ResourceManager.GetString("menu_advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset YubiKey PIV.
        /// </summary>
        internal static string menu_advanced_reset {
            get {
                return ResourceManager.GetString("menu_advanced_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show profiles.
        /// </summary>
        internal static string menu_advanced_show_profiles {
            get {
                return ResourceManager.GetString("menu_advanced_show_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string menu_file {
            get {
                return ResourceManager.GetString("menu_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string menu_file_quit {
            get {
                return ResourceManager.GetString("menu_file_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string menu_help_about {
            get {
                return ResourceManager.GetString("menu_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect PIN entered..
        /// </summary>
        internal static string statusbar_pin_incorrect {
            get {
                return ResourceManager.GetString("statusbar_pin_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YubiKey does not conform to requirements. Please correct..
        /// </summary>
        internal static string statusbar_requirementnotmet {
            get {
                return ResourceManager.GetString("statusbar_requirementnotmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select YubiKey and verify PIN to continue..
        /// </summary>
        internal static string statusbar_select_yubikey_and_verify_pin {
            get {
                return ResourceManager.GetString("statusbar_select_yubikey_and_verify_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify PIN before switching tabs..
        /// </summary>
        internal static string statusbar_verifypin {
            get {
                return ResourceManager.GetString("statusbar_verifypin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YubiKey PUK is not blocked, please block to proceed.
        /// </summary>
        internal static string statusbar_YubiKey_PUK_not_blocked {
            get {
                return ResourceManager.GetString("statusbar_YubiKey_PUK_not_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PIN.
        /// </summary>
        internal static string tab2_button_changepin {
            get {
                return ResourceManager.GetString("tab2_button_changepin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm PIN:.
        /// </summary>
        internal static string tab2_label_confirmpin {
            get {
                return ResourceManager.GetString("tab2_label_confirmpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PIN:.
        /// </summary>
        internal static string tab2_label_newpin {
            get {
                return ResourceManager.GetString("tab2_label_newpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance.
        /// </summary>
        internal static string tab2_label_Status {
            get {
                return ResourceManager.GetString("tab2_label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting update.
        /// </summary>
        internal static string tab2_status_awaiting {
            get {
                return ResourceManager.GetString("tab2_status_awaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YubiKey is meets tequirements..
        /// </summary>
        internal static string tab2_status_meets_requirements {
            get {
                return ResourceManager.GetString("tab2_status_meets_requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN not complex enough, please change.
        /// </summary>
        internal static string tab2_status_pin_complexity_not_meet {
            get {
                return ResourceManager.GetString("tab2_status_pin_complexity_not_meet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update number of possible PIN retires..
        /// </summary>
        internal static string tab2_status_pin_retry_count {
            get {
                return ResourceManager.GetString("tab2_status_pin_retry_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUK is not blocked, please block PUK..
        /// </summary>
        internal static string tab2_status_puk_not_blocked {
            get {
                return ResourceManager.GetString("tab2_status_puk_not_blocked", resourceCulture);
            }
        }
    }
}
